const frases = [
    'Só existe uma coisa que te separa do seu objetivo: sua capacidade',
    'Ninguém precisa te humilhar, um espelho já faz isso',
    'Muitos vão te dizer que você não vai conseguir, acredite neles',
    'Se alguém te ofendeu sem você merecer, volte lá e mereça',
    'Planeja os erros do futuro',
    'Nunca se esqueça: Você é limitado!',
    'Nenhum obstáculo é grande para quem desiste',
    'Não seja foda, desista!',
    'Jesus te ama porque não convive com você',
    'Sonho é quando percebemos que é impossível realizá-lo',
    'Você não é incrível, e muito menos especial',
    'Você não pode tudo',
    'Lembre-se: Se fosse fácil você não faria',
    'Dias ruins são necessários para termos dias piores',
    'Os sonhos antecedem os seus fracassos',
    'Desiste não. Tudo tem um momento certo para dar errado',
    'O que antes era inacreditável, agora está impossível',
    'Daqui a um ano você vai desejar ter desistido hoje',
    'Não tenha medo do fracasso, tenha certeza',
    'Mais um dia a menos',
    'Não faça hoje o que você pode fazer amanhã',
    'Um dia você está por baixo, no outro, você não está por cima',
    'O primeiro passo para a derrota é começar',
    'Vai! Se der medo, não vai',
    'O caminho é longo, mas a derrota é certa',
    'Não há nada tão inalcançável quanto seus sonhos',
    'As coisas podem piorar. Você que não tem imaginação',
    'Nem tudo está perdido. Muito ainda há pra se perder',
    'Não desanime com a derrota de hoje, amanhã tem outra',
    'Não deixe para amanhã o que você pode deixar pra lá.',
    'Malhar pra quê? Volte a dormir',
    'Um passo de cada vez rumo a derrota eminente',
    'Nunca deixe de desistir dos seu sonhos',
    'Se alguém quiser te derrubar na vida, tem que te levantar primeiro',
    'Não deixe que os outros digam que você não consegue, diga você mesmo',
    'Você não é tão fracassado como todo mundo pensa. Você é bem pior',
    'Nunca permita que uma mensagem motivacional estúpida alegre seu dia de merda',
    'Você é capaz de perder tudo, mesmo que não tenha conquistado nada',
    'Nenhuma solução é maior que o seu problema',
    'Você é mais fraco do que pensa e mais limitado do que imagina',
    'Resiliência: A incrível arte de se foder e continuar fodido',
    'Se você ama o que faz mude de área. Profissional bom é profissional com ódio. Não é atoa que o contrário de profissional é amador',
    'É hora de dar razão para aqueles que duvidaram de você',
    'Eu sei que má notícia gosta de companhia, mas as minhas andam de mutirão',
    'Na mala da vida, você é o xampu que abre a tampa e sai sujando e estragando tudo',
    'De longe você parecia feio, de perto você parece que está de longe',
    'Você está usando esse app mesmo? É por isso que ninguém sentava contigo no recreio!',
    'Não se preocupe. Na hora certa, tudo vai dar errado.',
    'O mérito da derrota é todo seu, orgulhe-se.',
    'Por causa de gente como você que na caixa de ovo vem escrito "Contém ovo"',
    'A vida é 10% o que acontece com você e 90% o que aconteceria se você tivesse dinheiro.',
    'Na subida para o seu sucesso, o elevador está quebrado, a escada está escorregadia e, de vez em quando, passa alguém subindo apressado e quase te derrubando no caminho.',
    'Você não pode mudar o seu passado, mas pode estragar seu futuro.',
    'O cartão de crédito está aí para quebrar seu galho. Aí depois ele pega o galho e dá bem na sua cabeça.',
    'A recompensa pelo bom trabalho é mais trabalho.',
    'A vida é um lindo conto de falhas.',
    'A inteligência artificial só não é mais incrível do que a sua burrice natural.',
    'Anime-se,tudo de ruim que você passou até agora está te preparando para algo pior.',
    'Ano novo, vida nova e mais 365 oportunidades de fazer besteira.',
    'Procrastinar é acreditar no potencial do seu "eu" de amanhã e se enganar por vários dias seguidos.',
    'Na viagem da vida, seu GPS está quebrado, você está sem co-piloto, e o carro bem que precisa de uma revisão.',
    'Hoje é o primeiro dia do resto da sua vida. Mas ontem também foi, e veja como acabou.',
    'A vida é o que acontece quando você está ocupado lendo frases motivacionais.',
    'É tudo uma ladeira abaixo a partir daqui.',
    'Pode ser que o seu propósito na vida seja servir de aviso para os outros.',
    'As piores coisas da sua vida provavelmente ainda não aconteceram com você.',
    'Tente bastante e não se preocupe se falhar, porque todos esperam isso.',
    'A estrada para o sucesso está sempre em construção.',
    'Será fácil? Não. Vale a pena? Absolutamente não!',
    'Você tentou o seu melhor e falhou miseravelmente. A lição é: nunca tente.',
    'Quando as coisas ficam difíceis, as difíceis ficam ainda mais difíceis.',
    'O primeiro passo para o fracasso é tentar.',
    'Aqueles que duvidam de sua capacidade provavelmente têm um motivo válido.',
    'A única coisa que todas as suas falhas têm em comum é você.',
    'Sua vida só sobe para que você possa cair de uma nova altura.',
    'Vida é dor. Qualquer pessoa que diga o contrário está vendendo alguma coisa.',
    'Se você nunca tentar nada novo, perderá muitas das grandes decepções da vida.',
    'Sempre peça dinheiro emprestado a um pessimista. Ele não vai esperar pelo dinheiro de volta.',
    'Todos os dias é sexta-feira quando você está desempregado.',
    'Se você odeia seu trabalho, existe um grupo de apoio para isso chamado Todomundo, e eles se encontram em um bar.',
    'Expectativa é igual paçoca, do nada esfarela tudo.',
    'Você usa esse App? Agora você sabe porque o Uber cancela sua corrida.',
    'Relaxa, porque daqui para frente é só para trás.',
    'Tem gente, igual a você, que é igual nuvem. A gente olha e vê um animal.',
    'A verdade dói, mas precisa ser dita: "Não será desta vez".',
    'É só uma fase ruim, logo vai piorar.',
    'Nunca foi azar, sempre foi incompetência!',
    'O problema não está na segunda-feira, está na sua vida.',
    'Acreditar que você consegue já é meio caminho para o fracasso.',
    'Considere a procrastinação. Quem não faz nada, não erra.',

];

module.exports = frases;